#!/usr/bin/env bash

openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -keyout userfacing.key -out userfacing.crt -subj "/C=GB/ST=Cardiff/L=Cardiff/O=Test/OU=Test/CN=pi.local"

openssl pkcs12 -export -out idp-userfacing.p12 -inkey userfacing.key -in userfacing.crt

mv idp-userfacing.p12 shibboleth-idp/credentials

rm userfacing.key
rm userfacing.crt